trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: self
    - repository: AzureTemplates # ID used to reference pipeline templates below
      type: git
      name: azure-templates

variables:
  vmImageName: 'ubuntu-latest'

  # Variables
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPR: $[eq(variables['Build.Reason'], 'PullRequest')]
  workingDirectory: $(System.DefaultWorkingDirectory)

stages:
  - stage: Test
    displayName: Run tests
    jobs:
      - template: pipelines/js-test.yaml@AzureTemplates
        parameters:
          vmImageName: $(vmImageName)
          workingDirectory: $(workingDirectory)

  - stage: Publish
    displayName: Build and Publish
    condition: and(succeeded(), and(eq(variables.isMain, 'true'), eq(variables.isPR, 'false')))
    dependsOn: Test
    jobs:
      - template: pipelines/publish-package.yaml@AzureTemplates
        parameters:
          vmImageName: $(vmImageName)
          workingDirectory: $(workingDirectory)
